variable "project" {
  description = "Project name; prefixes every resource name and is the stable service name."
  type        = string
  default     = "event-platform"
}

variable "environment" {
  description = "Environment name (local, dev, staging, prod)."
  type        = string
}

variable "owner" {
  description = "Value of the owner tag."
  type        = string
  default     = "platform-team"
}

variable "is_local" {
  description = "True when deploying to LocalStack (relaxes retention/removal settings)."
  type        = bool
  default     = false
}

variable "log_retention_days" {
  type    = number
  default = 14
}

variable "translator_timeout_seconds" {
  type    = number
  default = 30
}

variable "handler_timeout_seconds" {
  type    = number
  default = 30
}

variable "max_receive_count" {
  description = "SQS redrive attempts before a message goes to the DLQ."
  type        = number
  default     = 3
}

variable "rule_retry_attempts" {
  description = "EventBridge rule target retry attempts."
  type        = number
  default     = 185
}

variable "rule_max_event_age_seconds" {
  type    = number
  default = 86400
}

variable "archive_batch_size" {
  description = "Archive writer SQS batch size."
  type        = number
  default     = 1000
}

variable "archive_batching_window_seconds" {
  description = "Archive writer batching window (default 60s)."
  type        = number
  default     = 60
}

variable "archive_writer_timeout_seconds" {
  type    = number
  default = 300
}

variable "archive_max_concurrency" {
  type    = number
  default = 2
}

variable "idempotency_ttl_seconds" {
  type    = number
  default = 604800
}

variable "iceberg_rest_uri" {
  description = "Iceberg REST catalog URI. Empty = S3 Tables endpoint for the current region."
  type        = string
  default     = ""
}

variable "iceberg_warehouse" {
  description = "Catalog warehouse. Empty = the table bucket ARN (S3 Tables). LocalStack uses <account>:s3tablescatalog/<bucket>."
  type        = string
  default     = ""
}

variable "iceberg_sigv4" {
  description = "Sign catalog requests with SigV4 (true in AWS, false on LocalStack)."
  type        = bool
  default     = true
}

variable "iceberg_s3_endpoint" {
  description = "Override for the S3 endpoint used for Iceberg data files (LocalStack only)."
  type        = string
  default     = ""
}

variable "alarm_email" {
  description = "Optional email subscribed to the alarm topic."
  type        = string
  default     = ""
}

variable "registry_file" {
  description = "JSON export of src/domain/registry.py (generated by task build)."
  type        = string
  default     = "../build/registry.json"
}

variable "build_dir" {
  description = "Directory holding the bundled Lambda code (task build)."
  type        = string
  default     = "../build"
}

variable "image_tag" {
  description = "Tag for the archive writer image; empty = content hash of its sources."
  type        = string
  default     = ""
}
